#### general settings
name: EDVR_M_woTSA_3dD
# name: EDVRwoTSA_debug
use_tb_logger: true
model: video_3d_D
distortion: sr
scale: 4
gpu_ids: [0]
# gpu_ids: [0,1,2,3,4,5,6,7]
no_log: true
auto_resume: true

#### datasets
datasets:
  train:
    name: REDS
    mode: MultiREDS
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /home/dengpanfu/SR/mmsr/datasets/REDS/train_sharp
    dataroot_LQ: /home/dengpanfu/SR/mmsr/datasets/REDS/train_sharp_bicubic
    cache_keys: ~
    ratio: 200

    N_frames: 7
    valid_nf: 5
    use_shuffle: true
    n_workers: 0 # per GPU
    batch_size: 4
    GT_size: 256
    LQ_size: 64
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
## network_G ##
network_G:
  which_model_G: MultiEDVR
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: false
  w_TSA: false
## network_D ##
network_D:
  which_model_D: DCN3D
  input_nc: 3
  ndf: 64
  n_layers: 3
  num_d: 1
  use_sigmoid: false
  max_ndf: 256
  conv_type: normal

#### path
path:
  pretrain_model_G: ~
  pretrain_model_D: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme_G: CosineAnnealingLR_Restart
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  lr_scheme_D: StepLR
  beta1_D: 0.
  beta2_D: 0.99
  lr_step_D: 15000
  lr_gamma_D: 0.5
  niter: 600000
  warmup_iter: -1  # -1: no warm up
  T_period_G: [150000, 150000, 150000, 150000]
  restarts_G: [150000, 300000, 450000]
  restart_weights_G: [1, 1, 1]
  eta_min_G: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  gan_type: lsgan
  gan_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
