#### general settings
name: MetaEDVR_M_woTSA_fixEdvr_1
# name: EDVRwoTSA_debug
use_tb_logger: true
model: meta_video
distortion: sr
scale: -1
gpu_ids: [1]
# gpu_ids: [0,1,2,3,4,5,6,7]
# no_log: true

#### datasets
datasets:
  train:
    name: REDS
    mode: MetaREDS
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: ../datasets/REDS/train_sharp_wval.lmdb
    dataroot_LQ: ../datasets/REDS/LR_x1_x6.lmdb
    # dataroot_LQ: ../datasets/REDS/train_sharp_bicubic_wval.lmdb
    cache_keys: ~
    ratio: 300

    N_frames: 5
    use_shuffle: true
    n_workers: 0 # per GPU
    batch_size: 2
    GT_size: 256
    LQ_size: 64
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  which_model_G: MetaEDVR
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: false
  w_TSA: false

#### path
path:
  # pretrain_model_G: ../experiments/pretrained_models/EDVR_REDS_SR_M_woTSA.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  edvr_lr_mult: 0
  lr_G: !!float 1e-4
  lr_scheme: StepLR
  lr_step: 150000
  lr_gamma: 0.5
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1  # -1: no warm up

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
